apiVersion: v1
kind: ConfigMap
metadata:
  name: job-service-config
  namespace: job-scheduler
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: job-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
      - name: job-service
        image: boroleujval4/job_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: job-service-config
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 40   # increase to give time for startup
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
  namespace: job-scheduler
spec:
  type: NodePort
  selector:
    app: job-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31001 # NodePort for external access
  type: NodePort